/**
 * Mock product data for testing display across the storefront.
 * Structure matches ProductCardData / LocalProduct from lib/products.ts.
 * Used by /dev/test-proizvodi - NOT stored in database.
 */

import type { ProductCardData } from "./products";
import type { LocalProduct } from "./products";

export const MOCK_PRODUCTS_CARDS: ProductCardData[] = [
  {
    id: "mock-1",
    slug: "mock-basic-product",
    name: "Premium pamučna majica",
    price: 3490,
    salePrice: null,
    image1: null,
    onSale: false,
    novo: false,
    category: { name: "Majice" },
    brand: { name: "Demo Brand" },
  },
  {
    id: "mock-2",
    slug: "mock-sale-product",
    name: "Sportske patike Pro",
    price: 8990,
    salePrice: 5990,
    image1: null,
    onSale: true,
    novo: false,
    category: { name: "Patike" },
    brand: { name: "Demo Brand" },
  },
  {
    id: "mock-3",
    slug: "mock-new-product",
    name: "Elegantna kožna torba",
    price: 7490,
    salePrice: null,
    image1: null,
    onSale: false,
    novo: true,
    category: { name: "Torbe" },
    brand: { name: "Demo Brand" },
  },
];

/**
 * Full LocalProduct for product detail page.
 * Returned when fetchProductBySlug is called with mock slug.
 */
export const MOCK_PRODUCTS_FULL: Record<string, LocalProduct> = {
  "mock-basic-product": {
    id: "mock-1",
    name: "Premium pamučna majica",
    slug: "mock-basic-product",
    description: "Visokokvalitetna pamučna majica za svakodnevno nošenje.",
    sku: "MOCK-001",
    price: 3490,
    salePrice: null,
    image1: null,
    image2: null,
    image3: null,
    category: { id: "mock-cat", name: "Majice", slug: "majice" },
    brand: { id: "mock-brand", name: "Demo Brand", slug: "demo-brand" },
    gender: "unisex",
    active: true,
    featured: false,
    onSale: false,
    novo: false,
    sizes: [
      { size: "S", stock: 5 },
      { size: "M", stock: 8 },
      { size: "L", stock: 4 },
      { size: "XL", stock: 2 },
    ],
    color: "Crna",
    colorHex: "#000000",
    material: "100% pamuk",
    weight: 200,
    length: null,
    width: null,
    height: null,
    countryOfOrigin: null,
    careInstructions: "Pranje na 30°C.",
    barcode: null,
    tags: ["mock", "test"],
    metaTitle: null,
    metaDescription: null,
  },
  "mock-sale-product": {
    id: "mock-2",
    name: "Sportske patike Pro",
    slug: "mock-sale-product",
    description: "Lagane sportske patike za trčanje i svakodnevnu upotrebu.",
    sku: "MOCK-002",
    price: 8990,
    salePrice: 5990,
    image1: null,
    image2: null,
    image3: null,
    category: { id: "mock-cat-2", name: "Patike", slug: "patike" },
    brand: { id: "mock-brand", name: "Demo Brand", slug: "demo-brand" },
    gender: "muski",
    active: true,
    featured: false,
    onSale: true,
    novo: false,
    sizes: [
      { size: "42", stock: 5 },
      { size: "43", stock: 4 },
    ],
    color: "Bela",
    colorHex: "#FFFFFF",
    material: "Tekstil / sintetika",
    weight: 350,
    length: null,
    width: null,
    height: null,
    countryOfOrigin: null,
    careInstructions: null,
    barcode: null,
    tags: ["mock", "akcija"],
    metaTitle: null,
    metaDescription: null,
  },
  "mock-new-product": {
    id: "mock-3",
    name: "Elegantna kožna torba",
    slug: "mock-new-product",
    description: "Prostrana kožna torba elegantnog dizajna.",
    sku: "MOCK-003",
    price: 7490,
    salePrice: null,
    image1: null,
    image2: null,
    image3: null,
    category: { id: "mock-cat-3", name: "Torbe", slug: "torbe" },
    brand: { id: "mock-brand", name: "Demo Brand", slug: "demo-brand" },
    gender: "zenski",
    active: true,
    featured: false,
    onSale: false,
    novo: true,
    sizes: [
      { size: "One Size", stock: 10 },
    ],
    color: "Braon",
    colorHex: "#8B4513",
    material: "Prirodna koža",
    weight: 420,
    length: 30,
    width: 12,
    height: 25,
    countryOfOrigin: null,
    careInstructions: "Čistiti suvom krpom.",
    barcode: null,
    tags: ["mock", "novo"],
    metaTitle: null,
    metaDescription: null,
  },
};
